services:
  web:
    build: ./backend
    ports:
      - "5000:5000" # mapping the external port 5555 to container's internal port 5000 (on your computer use localhost:5555)
    environment: # environment variables required for flask
      - FLASK_ENV=development
      - FLASK_APP=endPoints.py
    volumes:
      - ./backend/App:/app # similar to below, this means when we make flask changes, it reloads in container
    command: flask run --host=0.0.0.0 --reload # this overrides the CMD in the Dockerfile and runs flask
  frontend:
    build: ./frontend
    ports:
      - "3333:3000" # mapping the external port 3333 to container's internal port 3000 (on your computer use localhost:3333)
    volumes: # every time you make a change, this will reload the changes in the container
      - ./frontend/src:/usr/src/app/src # write these as ./<path to folder>:/<path to folder in container>
    environment:
      - REACT_APP_BACKEND_URL=http://127.0.0.1:5000 # this defines the URL the frontend makes requests to
