name: Python application

on:
  push:
    branches: [ "CD_CD" ]
  pull_request:
    branches: [ "CD_CD" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.4"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/App/requirements.txt

      - name: Run tests
        run: |
          cd backend/Tests
          pytest tests.py
